### ISSUE TITLE
Update for Bootstrap 3.3.0?

### ISSUE THREAD

**Issue by tjwudi** [jozefizso/bower-bootstrap-less#5]

**Comment by igorlino** [comment]
@tjwudi there is a workaround feature ('overrides'), to getting the LESS of bootstrap relying only on the original/official bootstrap package dependency. (which has always the latest)

Add the following to your bower.json file after including the bootstrap dependency.
"overrides": {
        "bootstrap" : {
            "main": [
                "less/bootstrap.less",
                "dist/fonts/glyphicons-halflings-regular.eot",
                "dist/fonts/glyphicons-halflings-regular.svg",
                "dist/fonts/glyphicons-halflings-regular.ttf",
                "dist/fonts/glyphicons-halflings-regular.woff",
                "dist/fonts/glyphicons-halflings-regular.woff2"
            ],
        }
    }

**Comment by tjwudi** [comment]
Thanks, this helps! @igorlino
